DROP TABLE IF EXISTS Faculty_Employee ;
DROP TABLE IF EXISTS Application ;
DROP TABLE IF EXISTS Faculty ;
DROP TABLE IF EXISTS Employee ;
DROP TABLE IF EXISTS Benefit ;
DROP TABLE IF EXISTS Applicant ;
DROP TABLE IF EXISTS Passport ;
DROP TABLE IF EXISTS Certificate ;